### ISSUE TITLE
Error: Unable to resolve action `pandoc/actions@{main}`, unable to find version `{main}`

### ISSUE THREAD

**Issue by yagarea** [pandoc/actions#2]
I tried to use this action in my repo like this:
```yaml
name: Build kategorie pdf
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Install
        uses: pandoc/actions/setup@{main}
        with:
          version: 3.1
      - name: Pandoc version check
        run: pandoc --version
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Download statement.lua
        run: |
          mkdir -p ~/.pandoc/filters
          wget -O ~/.pandoc/filters/statement.lua https://raw.githubusercontent.com/dialoa/statement/main/statement.lua
      - name: Compile Markdown to PDF
        run: |
          pandoc -L ~/.pandoc/filters/statement.lua -s kategorie.md -o kategorie.pdf
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: compiled-pdf
          path: kategorie.pdf
```

and I got this output:
```yaml
Current runner version: '2.313.0'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Error: Unable to resolve action `pandoc/actions@{main}`, unable to find version `{main}`
```
